apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: ea-ms
spec:
  selector:
    app: employee-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: ea-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: ea-management/employee-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: mysql.default
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: EUREKA_SERVER_URL
              value: http://eureka-service.ea-ms.svc.cluster.local:8761/eureka/
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 70
            periodSeconds: 20
