apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ea-ms
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 9999
      targetPort: 9999
      nodePort: 30099
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: ea-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: ea-management/gateway-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          env:
            - name: EUREKA_SERVER_URL
              value: http://eureka-service.ea-ms.svc.cluster.local:8761/eureka/
            - name: RATE_LIMIT_MAX_REQUESTS
              value: "5"
            - name: RATE_LIMIT_WINDOW_SECONDS
              value: "30"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          readinessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 70
            periodSeconds: 20
